/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IAutoCompleteItem,
} from './components/traim-autocomplete/interfaces';

export namespace Components {
  interface TraimAccordion {
    'useCounter': boolean;
  }
  interface TraimAccordionPane {
    'close': () => Promise<void>;
    'header': string;
    'isOpen': () => Promise<boolean>;
    'open': boolean;
    'show': () => Promise<void>;
  }
  interface TraimAutocomplete {
    'placeholder': string;
    'setItems': (items: IAutoCompleteItem[]) => Promise<void>;
  }
  interface TraimTimeline {
    'alternate': boolean;
    'loading': boolean;
  }
  interface TraimTimelineItem {
    'last': boolean;
    'left': boolean;
    'loading': boolean;
    'type': string;
  }
}

declare global {


  interface HTMLTraimAccordionElement extends Components.TraimAccordion, HTMLStencilElement {}
  var HTMLTraimAccordionElement: {
    prototype: HTMLTraimAccordionElement;
    new (): HTMLTraimAccordionElement;
  };

  interface HTMLTraimAccordionPaneElement extends Components.TraimAccordionPane, HTMLStencilElement {}
  var HTMLTraimAccordionPaneElement: {
    prototype: HTMLTraimAccordionPaneElement;
    new (): HTMLTraimAccordionPaneElement;
  };

  interface HTMLTraimAutocompleteElement extends Components.TraimAutocomplete, HTMLStencilElement {}
  var HTMLTraimAutocompleteElement: {
    prototype: HTMLTraimAutocompleteElement;
    new (): HTMLTraimAutocompleteElement;
  };

  interface HTMLTraimTimelineElement extends Components.TraimTimeline, HTMLStencilElement {}
  var HTMLTraimTimelineElement: {
    prototype: HTMLTraimTimelineElement;
    new (): HTMLTraimTimelineElement;
  };

  interface HTMLTraimTimelineItemElement extends Components.TraimTimelineItem, HTMLStencilElement {}
  var HTMLTraimTimelineItemElement: {
    prototype: HTMLTraimTimelineItemElement;
    new (): HTMLTraimTimelineItemElement;
  };
  interface HTMLElementTagNameMap {
    'traim-accordion': HTMLTraimAccordionElement;
    'traim-accordion-pane': HTMLTraimAccordionPaneElement;
    'traim-autocomplete': HTMLTraimAutocompleteElement;
    'traim-timeline': HTMLTraimTimelineElement;
    'traim-timeline-item': HTMLTraimTimelineItemElement;
  }
}

declare namespace LocalJSX {
  interface TraimAccordion {
    'onToggle'?: (event: CustomEvent<any>) => void;
    'useCounter'?: boolean;
  }
  interface TraimAccordionPane {
    'header'?: string;
    'onTogglepane'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
  }
  interface TraimAutocomplete {
    'onSearch'?: (event: CustomEvent<any>) => void;
    'onSelect'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
  }
  interface TraimTimeline {
    'alternate'?: boolean;
    'loading'?: boolean;
  }
  interface TraimTimelineItem {
    'last'?: boolean;
    'left'?: boolean;
    'loading'?: boolean;
    'type'?: string;
  }

  interface IntrinsicElements {
    'traim-accordion': TraimAccordion;
    'traim-accordion-pane': TraimAccordionPane;
    'traim-autocomplete': TraimAutocomplete;
    'traim-timeline': TraimTimeline;
    'traim-timeline-item': TraimTimelineItem;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'traim-accordion': LocalJSX.TraimAccordion & JSXBase.HTMLAttributes<HTMLTraimAccordionElement>;
      'traim-accordion-pane': LocalJSX.TraimAccordionPane & JSXBase.HTMLAttributes<HTMLTraimAccordionPaneElement>;
      'traim-autocomplete': LocalJSX.TraimAutocomplete & JSXBase.HTMLAttributes<HTMLTraimAutocompleteElement>;
      'traim-timeline': LocalJSX.TraimTimeline & JSXBase.HTMLAttributes<HTMLTraimTimelineElement>;
      'traim-timeline-item': LocalJSX.TraimTimelineItem & JSXBase.HTMLAttributes<HTMLTraimTimelineItemElement>;
    }
  }
}


